# Generated by Django 4.0.2 on 2022-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BigIntegerField(default=True, verbose_name='активный'),
        ),
    ]
