# Generated by Django 4.0.2 on 2022-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('IN_PROCESSING', 'В обработке'), ('AWAITING_PAYMENT', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('READY', 'Готов к выдаче'), ('CANCELED', 'Отменен'), ('FINISHED', 'Выдан')], default='CREATED', max_length=20, verbose_name='статус'),
        ),
    ]
